id: ID7C9B9C4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T20:12:19+00:00'
last_modified: '2022-06-08T12:14:05.845107+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1016951
  title: འདུལ་ཊཱིཀ་རིན་ཆེན་འཕྲེང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    331A:
      image_group_id: I01JW173
      title: ''
      total_pages: 600
      order: 1
      base_file: 331A.txt
    F5AB:
      image_group_id: I01JW174
      title: ''
      total_pages: 468
      order: 2
      base_file: F5AB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
