id: ID7C9B9C4
legacy_id: P009608
ocr_import_info:
  bdrc_scan_id: W00EGS1016951
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T20:09:19'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T08:56:05.490536+00:00'
last_modified: 2022-08-29 14:34:55.728447
parser: null
source_metadata:
  id: http://purl.bdrc.io/resource/W00EGS1016951
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW00EGS1016951
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འདུལ་ཊཱིཀ་རིན་ཆེན་འཕྲེང་བ།
  author: དགེ་འདུན་གྲུབ་པ།
statistics:
  ocr_word_mean_confidence_index: 0.9664283770818924
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I01JW173:
    source_metadata:
      id: http://purl.bdrc.io/resource/I01JW173
      total_pages: 600
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I01JW173.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9668109760887105
    legacy_id: v001
  I01JW174:
    source_metadata:
      id: http://purl.bdrc.io/resource/I01JW174
      total_pages: 468
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I01JW174.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9658954410094479
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
